name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code from Repository
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: run Unit Test
        run: npm test
