name: 2. Integration Test

on:
  workflow_run:
    workflows: ["1. Unit Test"]
    types:
      - completed

jobs:
  run-integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Execute Integration Test
        run: node dist/IntegrationTest.js
